# Generated by Django 4.1.6 on 2023-02-09 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='baladiya',
            fields=[
                ('baladiya_name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_name', models.CharField(max_length=200)),
                ('description_cat', models.TextField(blank=True, max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('baladiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.baladiya')),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('wilaya_name', models.CharField(max_length=200)),
                ('wilaya_matricule', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('Service_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='photos/Service')),
                ('is_avalaible', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('baladiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.baladiya')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sevice', to=settings.AUTH_USER_MODEL)),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.wilaya')),
            ],
        ),
        migrations.CreateModel(
            name='Createservice',
            fields=[
                ('Service_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('images', models.ImageField(upload_to='photos/Ser')),
                ('your_sertificate', models.ImageField(upload_to='photos/Competence')),
                ('is_avalaible', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('baladiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.baladiya')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sev', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.wilaya'),
        ),
        migrations.AddField(
            model_name='baladiya',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.wilaya'),
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('subject', models.CharField(blank=True, max_length=100)),
                ('review', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField()),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sevicess', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'unique_together': {('owner', 'service')},
            },
        ),
    ]
